# Dockerfile.bun
FROM oven/bun:latest

WORKDIR /home/app

COPY package.json .
COPY bun.lock .


# Only install prod dependencies if you're building a production image
# For development, 'bun install' handles dev dependencies too
RUN bun install

COPY . .

RUN apt-get update && apt-get install -y openssl

RUN bunx prisma generate


EXPOSE 6001

CMD [ "bun", "run", "dev" ]