export const shopCategories = [
  { value: "restaurant", label: "Restaurants & Cafés" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "furniture", label: "Furniture & Home Decor" },
  { value: "automotive", label: "Automotive & Accessories" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys & Games" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "hardware", label: "Hardware & Tools" },
  { value: "pet", label: "Pet Supplies & Services" },
  { value: "medical", label: "Medical & Pharmacy" },
  { value: "clothing", label: "Apparel & Fashion" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "grocery", label: "Grocery & Supermarket" },
  { value: "home_services", label: "Home Services" },
  { value: "real_estate", label: "Real Estate" },
  { value: "travel", label: "Travel & Accommodations" },
  { value: "finance", label: "Finance & Banking" },
  { value: "arts", label: "Arts & Entertainment" },
  { value: "education", label: "Education & Learning" },
  { value: "health", label: "Health & Wellness" },
  { value: "kids", label: "Kids & Baby" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "events", label: "Events & Planning" },
  { value: "gardening", label: "Gardening & Landscaping" },
  { value: "music", label: "Music & Instruments" },
];
